### ISSUE TITLE
Discord crash if you open the notes in friend list

### ISSUE THREAD

**Issue by xaiyadev** [Swishilicous/holy-notes#7]
If you want to open the Holy Notes in the freindlist section your discord crashes

**Comment by Swishilicous** [comment]
Does this still exist? I can't reproduce it lol

**Comment by xaiyadev** [comment]
Yes, it doesnt Crash really it pops Up a Windows that says you Need to restart discord And this Happens everytime you want to Go to your Friendslist

**Comment by Swishilicous** [comment]
could you show me a screenshot i can't reproduce

**Comment by xaiyadev** [comment]
I fixed the problem, I didn't know what it really was but it disappeared just one day, thanks for the help I guess
